### ISSUE TITLE
Need specification about the CeleX5.

### ISSUE THREAD

**Issue by eleboss** [CelePixel/CeleX5-MIPI#1]
Dear developer,

I am a researcher luckily have the latest version of CeleX5 DVS in hand.

Recently, I am working on the denoising algorithm for the event-based image, using CeleX5. However, after having carefully checked the documents in this Github repo and done many searches using both Google and IEEE Xplore, I still couldn't find a detailed specification table for this camera(like the below one).
![parameter](https://user-images.githubusercontent.com/19730939/55626782-07b2e980-57df-11e9-8b9c-e558b0b58bad.png)
Without, these data, I can't clearly state my algorithm in the research paper.
From the previous papers, I can clearly see the specification of a camera like DAVIS and other sensors. 

So could you please give me some specifications(especially the latency) about this world leading camera? 
Or maybe I missed some important information, It will be good if you can point out where I can find these data.

Thank you for your attention.

Best.

**Comment by CelePixel** [comment]
@eleboss Thanks for your question. The latency in CeleX5 is **1us**, which is the time interval from the event being detected by a pixel to being transmitted off chip.

**Comment by eleboss** [comment]
Hi, CelePixel.

Thank you for your reply.

However, 1us doesn't seem very convincing to me. 

Usually, people use nominal latency and minimum latency to define the latency of event-based camera and sensors can have different latency under different illuminations. So the latency can never be a constant value. So let me just assume your 1us is the minimum latency then what is the nominal latency and maximum latency of this sensor?
The pic below and the latency of other sensors in my previous post can give you a very clear view of my statement.
![Screenshot from 2019-04-16 22-02-01](https://user-images.githubusercontent.com/19730939/56216052-4b390d80-6093-11e9-97ca-24e1b11c5cda.png)
So would you please tell me under what illumination conditions have you get this 1us latency? And the nominal, maximum and minimum latency of this sensor?

Sorry for these rude questions. But as a researcher, I must find out what actually happens inside this sensor. Otherwise, the data post in Celex website is not trustable.

BTW, I find another strange question. Usually, the events detected are **Discrete** in the time axis, which means there are few chances that multiple events can have the same timestamp during the whole movement of an event-camera. I manually check many open-dataset like MVSEC and ETHZ dataset. Their sensors are right about this point.
But if you carefully check the data in below pic(using a flashlight to activate every pixels of Celex camera at the same time), you will find the events in every column share the **exact same timestamp**. WEARED. It looks like that the camera can not process so many data at the same time, and apply **JUST ONE TIMESTAMP** to the whole col data. So could you please give me an explanation about this phenomenon, I hope I am wrong about this. But If I am right, this change may reject many algorithms because of the difference in the events data.
![fina](https://user-images.githubusercontent.com/19730939/56217009-0dd57f80-6095-11e9-8547-3edab49b372f.png)

Best.

**Comment by eleboss** [comment]
I start a new issue to discuss the another Q.
