### ISSUE TITLE
Events are not fully discrete.

### ISSUE THREAD

**Issue by eleboss** [CelePixel/CeleX5-MIPI#2]
I find another strange question. Usually, the events detected are **Discrete** in the time axis, which means there are few chances that multiple events can have the same timestamp during the whole movement of an event-camera. I manually check many open-dataset like MVSEC and ETHZ dataset. Their sensors are right about this point.
But if you carefully check the data in below pic(using a flashlight to activate every pixels of Celex camera at the same time), you will find the events in every column share the **exact same timestamp**. WEARED. It looks like that the camera can not process so many data at the same time, and apply **JUST ONE TIMESTAMP** to the whole col data. So could you please give me an explanation about this phenomenon, I hope I am wrong about this. But If I am right, this change may reject many algorithms because of the difference in the events data.
![fina](https://user-images.githubusercontent.com/19730939/56217009-0dd57f80-6095-11e9-8547-3edab49b372f.png)

**Comment by eleboss** [comment]
Simply give up.

**Comment by civilpat** [comment]
> Simply give up.

Hi eleboss, did you figure it out? @eleboss Do you think this is an issue for the CelePX5 camera? I am at the edge of purchasing this camera or DAVIS camera which has less pixels. Could you please give some advice? Thank you!
