### ISSUE TITLE
[Question] Capture both RGB frame and event frame at same time

### ISSUE THREAD

**Issue by gachiemchiep** [CelePixel/CeleX5-MIPI#3]
Hello developer. 
The celePixel demo at [youtube](https://www.youtube.com/watch?v=9AUtuKALVUA) , show separate rgb frame (of the left side) and event frame ( on the right side).
Is this captured by two different CelePixel camera ? 
We want to capture both rgb frame and event frame using only one camera. Is this possible ? 

Thank you.

**Comment by goncaloram** [comment]
Hello @gachiemchiep,  have you been able to accomplish this? If so, how did you do it?
Thanks in advance.

**Comment by gachiemchiep** [comment]
@goncaloram . We didn't purchase the camera. So we don't know how.
